<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Emily Schultz" />

<meta name="date" content="2023-02-15" />

<title>ESS 3500 R Handbook, Lesson 5</title>

<script src="site_libs/header-attrs-2.19/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">ESS 3500 R Handbook</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lessons
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="RHandbook_1.html">Lesson 1: Software installation</a>
    </li>
    <li>
      <a href="RHandbook_2.html">Lesson 2: R Basics</a>
    </li>
    <li>
      <a href="RHandbook_3.html">Lesson 3: Data frames</a>
    </li>
    <li>
      <a href="RHandbook_4.html">Lesson 4: Descriptive statistics</a>
    </li>
    <li>
      <a href="RHandbook_5.html">Lesson 5: Linear models</a>
    </li>
    <li>
      <a href="RHandbook_6.html">Lesson 6: Data visualization</a>
    </li>
    <li>
      <a href="RHandbook_7.html">Lesson 7: T-tests</a>
    </li>
    <li>
      <a href="RHandbook_8.html">Lesson 8: ANOVA</a>
    </li>
    <li>
      <a href="RHandbook_9.html">Lesson 9: Regressions</a>
    </li>
    <li>
      <a href="RHandbook_10.html">Lesson 10: Assumptions and transformations</a>
    </li>
    <li>
      <a href="RHandbook_11.html">Lesson 11: Multiple predictors</a>
    </li>
    <li>
      <a href="RHandbook_12.html">Lesson 12: Categorical data</a>
    </li>
  </ul>
</li>
<li>
  <a href="RHandbook_templates.html">R Templates</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">ESS 3500 R Handbook, Lesson 5</h1>
<h4 class="author">Emily Schultz</h4>
<h4 class="date">2023-02-15</h4>

</div>

<div id="TOC">
<ul>
<li><a href="#lesson-5-linear-models-in-r"
id="toc-lesson-5-linear-models-in-r">Lesson 5: LINEAR MODELS IN R</a>
<ul>
<li><a href="#discrete-predictor-variable"
id="toc-discrete-predictor-variable">5.1 Discrete predictor
variable</a></li>
<li><a href="#continuous-predictor-variable"
id="toc-continuous-predictor-variable">5.2 Continuous predictor
variable</a></li>
</ul></li>
</ul>
</div>

<div id="lesson-5-linear-models-in-r" class="section level2">
<h2>Lesson 5: LINEAR MODELS IN R</h2>
<p>Now that you have learned how to write statistical models
(hypotheses), you will learn how to build these models in R. In this
process, we will not only write the models, but we will get R to
<em>parameterize</em> the models for us. What I mean by this is that
once we set up the models, R will use our data to estimate the mean and
variance for the true distribution of the variable in our population of
interest. If we include predictor variables in our model, it will also
estimate how the predictor variable affects the mean of our
distribution.</p>
<div id="discrete-predictor-variable" class="section level3">
<h3>5.1 Discrete predictor variable</h3>
<p>We will start with an example with a discrete (categorical)
independent variable and a continuous dependent variable.</p>
<p>Start off by reading in the civu data set that we have worked with
before. Be sure to first set your working directory to the folder with
the civu dataset. Then use the <code>head</code> function to view the
top rows of the data set, as a reminder of what data we have in the data
frame.</p>
<pre class="r"><code>civu &lt;- read.csv(&quot;civu.csv&quot;)
head(civu)</code></pre>
<pre><code>##   herbivory plant_id density_2006 density_2007 survival_t.1
## 1         0       15           20            3            0
## 2         0        7           26            5            0
## 3         0       16           17            1            0
## 4         0       22           26            5            0
## 5         0       23           26            5            0
## 6         0       12           20            3            0</code></pre>
<p>In this example, we will work with the same question you tackled in
your Model Building Practice Problems: does insect herbivory affect the
density of thistle plants? For this example we will build 2 models: one
representing the null hypothesis and one representing the alternative
hypothesis. Then we will practice interpreting the output of the
models.</p>
<div id="null-model" class="section level4">
<h4>Null model</h4>
<p>Let’s start with the null hypothesis: herbivory does not affect the
density of thistles.</p>
<p>To build linear models in R, we will use a new function, the
<code>lm</code> function (short for “linear model”). The function
requires two arguments: the formula for our model and the data set. The
formula for our model needs to include the dependent variable on the
left side of the formula and the predictor variable(s) on the right side
of the formula. For our null model, saying that herbivory does not
affect density is the equivalent of saying that we do not need to use
herbivory as a predictor in the model. In this case, our null model will
therefore not have a predictor variable. We tell R this by putting a 1
in place of a predictor variable.</p>
<p>The full code to set up the model is as follows. We will save the
model as an object called “civu_null”.</p>
<pre class="r"><code>civu_null &lt;- lm(density_2006 ~ 1, civu)</code></pre>
<p>Now, lets view the basic output from this model. To do this, we
simply type the name of our model object.</p>
<pre class="r"><code>civu_null</code></pre>
<pre><code>## 
## Call:
## lm(formula = density_2006 ~ 1, data = civu)
## 
## Coefficients:
## (Intercept)  
##        34.6</code></pre>
<p>This simple output will tell us two things. It will first remind us
of the code we used to build the model, so we can see the independent
and dependent variables we included. Second, it will show us the
coefficients, or the parameters of our model. Because our null model did
not have any predictors, it just has a single coefficient, the
intercept, which in this case is 34.6. Remember, this model represents
the mean of the distribution of our data, so, based on our null model,
the mean density is 34.6, regardless of the herbivory treatment.</p>
</div>
<div id="alternative-model" class="section level4">
<h4>Alternative model</h4>
<p>Now, let’s compare this null model to our alternative model. Our
alternative model is that herbivory does affect the density, so this
time, we want it include it as a predictor in our model. We will then be
able to see how the herbivory treatment affects our estimate of the mean
density.</p>
<p>We set up the model in the same way we did for the null model, but
put our predictor variable in place of the 1.</p>
<pre class="r"><code>civu_alt &lt;- lm(density_2006 ~ herbivory, civu)
civu_alt</code></pre>
<pre><code>## 
## Call:
## lm(formula = density_2006 ~ herbivory, data = civu)
## 
## Coefficients:
## (Intercept)    herbivory  
##          21           17</code></pre>
<p>Now when we view the output, we see two coefficients. The intercept
(21) and the herbivory coefficient (17). If we wrote this model out as
an equation, it would be:</p>
<p><span class="math display">\[
\mu = 21 + 17*herbivory
\]</span> where is the mean density. Recall that the categorical
herbivory term in this equation can take on two values: 0 and 1. In this
case, 0 is the control group, which is herbivores present and 1 is the
treatment group, which is herbivores excluded. Therefore, the mean
density in the presence of herbivores is 21 and the mean density in the
absence of herbivores is <span
class="math inline">\(21+17=38\)</span>.</p>
</div>
<div id="model-variance" class="section level4">
<h4>Model variance</h4>
<p>We now have two models that describe the mean (or means) of our
data:</p>
<ol style="list-style-type: decimal">
<li>Null model: <span class="math inline">\(\mu=34.6\)</span></li>
<li>Alternative model: <span
class="math inline">\(\mu=21+17*herbivory\)</span></li>
</ol>
<p>But remember, to describe data using a normal distribution, we need
two parameters: the mean and the variance! We’ll now learn how to find
the variance (<span class="math inline">\(\sigma^2\)</span>) (and
standard deviation) in the model output. To do so, we will use the
<code>summary</code> function. The summary function will give us
additional output for our model. Most of the output we will learn about
later in the semester when we cover model testing. For now, we will just
pull out the standard deviation from the summary for each model as
follows:</p>
<pre class="r"><code>null_sd_civu &lt;- summary(civu_null)$sigma
alt_sd_civu &lt;- summary(civu_alt)$sigma</code></pre>
<p>We can then calculate the variance by squaring the standard
deviations:</p>
<pre class="r"><code>null_var_civu &lt;- null_sd_civu^2
alt_var_civu &lt;- alt_sd_civu^2</code></pre>
<p>This variance is specifically what we refer to as the residual
variance of the model, which we talked about earlier in the class. It is
the variation in our data that is not explained by the predictors we
included in our model. In this particular example, we can explain some
variation in thistle density by herbivore presence (which is why the
residual variance is lower in our alternative model than our null
model), but within each treatment groups, there is still unexplained
variation in density. In this type of model, we assume that the variance
is equal, or close to equal, in both of our treatment groups, so we just
have a single variance term.</p>
<p>We now have to complete models, with both mean and variance terms to
describe our data. If we write them out formally, they would look like
this, where <span class="math inline">\(N\)</span> indicates a normal
distribution:</p>
<p>Null model: <span class="math display">\[
density \sim N(\mu,\sigma^2)
\]</span> <span class="math display">\[
\mu = 34.6
\]</span> <span class="math display">\[
\sigma^2 = 12.16
\]</span></p>
<p>Alternative model: <span class="math display">\[
density \sim N(\mu,\sigma^2)
\]</span> <span class="math display">\[
\mu = 21 + 17*herbivory
\]</span> <span class="math display">\[
\sigma^2 = 10.09
\]</span></p>
</div>
</div>
<div id="continuous-predictor-variable" class="section level3">
<h3>5.2 Continuous predictor variable</h3>
<p>We will now move on to an example with a continuous independent
variable and a continuous dependent variable.</p>
<p>Read in the DataFrameExample data set that we have worked with
before. Be sure to first set your working directory to the folder with
the DataFrameExample data set. Because this data set has data on tree
growth, we will call it “tree”. Again use the <code>head</code> function
to view the top rows of the data set to remind yourself what data we
have in the data frame.</p>
<pre class="r"><code>tree &lt;- read.csv(&quot;DataFrameExample.csv&quot;)
head(tree)</code></pre>
<pre><code>##   Tree Year Number.cones Growth Temperature
## 1    A 2009            0   0.21        8.58
## 2    A 2010           14   0.26        8.67
## 3    A 2011            0   0.20        8.32
## 4    A 2012           35   0.15        9.68
## 5    A 2013           14   0.21        9.09
## 6    B 2009           64   0.21        7.28</code></pre>
<p>For this example, We will also work with the question you tackled in
your Model Building Practice Problems for this data set: does
temperature affect the growth of trees? Let’s build and interpret the
null and alternative models for this example! The procedure is the same
one used above, we will just interpret the output slightly
differently.</p>
<div id="null-model-1" class="section level4">
<h4>Null model</h4>
<p>Let’s start with the null hypothesis: temperature does not affect the
growth of trees.</p>
<p>As before, our null model will therefore not have a predictor
variable because we are assuming that temperature is not important for
the growth of trees.</p>
<p>The full code to set up the model is as follows:</p>
<pre class="r"><code>tree_null &lt;- lm( Growth ~ 1, tree)</code></pre>
<p>Now, lets view the basic output from this model.</p>
<pre class="r"><code>tree_null</code></pre>
<pre><code>## 
## Call:
## lm(formula = Growth ~ 1, data = tree)
## 
## Coefficients:
## (Intercept)  
##       0.206</code></pre>
<p>This output should look very similar to the output for the null model
for the civu data. It just has a single coefficient, the intercept
because we do not have any predictors. The mean tree growth, based on
our null model, is therefore 0.206.</p>
</div>
<div id="alternative-model-1" class="section level4">
<h4>Alternative model</h4>
<p>Now we’ll move on to our alternative model: temperature does affect
the tree growth. This time, we will include temperature in our model to
determine how the temperature affects tree growth.</p>
<p>We set up the model in the same way we did for the null model, but
this time including our temperature variable.</p>
<pre class="r"><code>tree_alt &lt;- lm(Growth ~ Temperature, tree)
tree_alt</code></pre>
<pre><code>## 
## Call:
## lm(formula = Growth ~ Temperature, data = tree)
## 
## Coefficients:
## (Intercept)  Temperature  
##     0.32926     -0.01497</code></pre>
<p>Here we again see two coefficients. The intercept and the temperature
coefficient (i.e., slope). If we wrote this model out as an equation, it
would be:</p>
<p><span class="math display">\[
\mu = 0.32926 - 0.01497*temperature
\]</span> where is the mean tree growth. The difference in the
interpretation for this model is that temperature is a continuous
variable, so it can take on a full range of values. Still, using this
equation, we would be able to calculate the mean tree growth for any
temperature value. We can also tell from the sign on the temperature
coefficient that as temperature increases, we would expect the tree
growth to decrease.</p>
</div>
<div id="model-variance-1" class="section level4">
<h4>Model variance</h4>
<p>Finally, we will calculate the residual variance for our two model,
so we can fully describe the distribution of our tree growth data.</p>
<pre class="r"><code>null_sd_tree &lt;- summary(tree_null)$sigma
alt_sd_tree &lt;- summary(tree_alt)$sigma

null_var_tree &lt;- null_sd_tree^2
alt_var_tree &lt;- alt_sd_tree^2</code></pre>
<p>We are now ready to write our full models, with both mean and
variance terms (remember, we just have one variance term for each
model), to describe our data.</p>
<p>Null model: <span class="math display">\[
growth \sim N(\mu,\sigma^2)
\]</span> <span class="math display">\[
\mu = 0.206
\]</span> <span class="math display">\[
\sigma^2 = 0.00098
\]</span></p>
<p>Alternative model: <span class="math display">\[
growth \sim N(\mu,\sigma^2)
\]</span> <span class="math display">\[
\mu = 0.32926 - 0.01497*temperature
\]</span> <span class="math display">\[
\sigma^2 = 0.00093
\]</span> In the next class, we will use these same examples to practice
visualizing our data and model output, so be sure to save your code from
this lesson, and make sure you add comments to your code so you remember
what you were doing at each step!</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
